
###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?sender=Lior

###

GET http://localhost:3000/posts/677acaa66909ab5af8ba2dbe

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Hello",
    "sender": "Lior",
    "content": "Hello World..."
}


###

PUT http://localhost:3000/posts/67757ca8ded1dd0ab69182de
Content-Type: application/json

{
    "title": "Updated Title",
    "sender": "Lior",
    "content": "Updated content..."
}


###

POST http://localhost:3000/comments
Content-Type: application/json

{
    "userId": "Kevin",
    "postId": "67757ca8ded1dd0ab69182de",
    "content": "My first comment"
}

###

GET http://localhost:3000/comments

###

GET http://localhost:3000/comments/677ae6bffe86caf6ab1e6123

###

PUT http://localhost:3000/comments/677ae6bffe86caf6ab1e6123
Content-Type: application/json

{
    "userId": "Kevin",
    "postId": "67757ca8ded1dd0ab69182de",
    "content": "My second comment"
}

###

DELETE http://localhost:3000/comments/677ae6bffe86caf6ab1e6123

###

GET http://localhost:3000/comments/post/67757ca8ded1dd0ab69182de

